filebeat.inputs:

- type: log

  enabled: true

  paths:
    - /logs/basic_log.txt
    - /logs/uwsgi.log

  multiline.pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}
  multiline.negate: true
  multiline.match: after

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["itsociety.su:5044"]
  index: ${COMPOSE_PROJECT_NAME}_filebeat_api

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~

