"""updated pair mark

Revision ID: 2dce5f1fef81
Revises: 04c6ae2e6763
Create Date: 2022-05-15 23:18:53.528939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dce5f1fef81'
down_revision = '04c6ae2e6763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pairing_mark', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pairing_mark', 'Event', ['event_id'], ['event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pairing_mark', type_='foreignkey')
    op.drop_column('pairing_mark', 'event_id')
    # ### end Alembic commands ###
